quoter/models.py
from flask_login import UserMixin

from . import db


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String, unique=True)
    username = db.Column(db.String, unique=True)
    first_name = db.Column(db.String)
    last_name = db.Column(db.String)
    password = db.Column(db.String)

quoter/models/post.py
from datetime import datetime

from quoter import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

quoter/models/user.py
from flask_login import UserMixin

from quoter import db


like_post = db.Table(
    "like_post",
    db.Column("user_id", db.ForeignKey('user.id'), primary_key=True),
    db.Column("post_id", db.ForeignKey('post.id'), primary_key=True),
)

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String, unique=True)
    username = db.Column(db.String, unique=True)
    first_name = db.Column(db.String)
    last_name = db.Column(db.String)
    password = db.Column(db.String)
    posts = db.relationship('Post', backref='user')
    likes = db.relationship('Post', secondary=like_post, backref='liked')

quoter/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField


class CreateForm(FlaskForm):
    content = TextAreaField()
    submit = SubmitField("Post")

class LikeForm(FlaskForm):
    submit = SubmitField("Like")

class UnlikeForm(FlaskForm):
    submit = SubmitField("Unlike")

quoter/users/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, StringField, PasswordField, SubmitField, BooleanField, validators


class RegisterForm(FlaskForm):
    email = EmailField()
    username = StringField()
    first_name = StringField()
    last_name = StringField()
    password = PasswordField("Password", [validators.EqualTo("confirm_password", "Passwords must match.")])
    confirm_password = PasswordField()
    submit = SubmitField("Register")

class LoginForm(FlaskForm):
    email = EmailField()
    password = PasswordField()
    remember = BooleanField("Remember Me")
    submit = SubmitField("Login")

quoter/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_migrate import Migrate


# Create and configure the app
app = Flask(__name__)
app.config ["SECRET_KEY"] = "dev"
app.config ["SQLALCHEMY_DATABASE_URI"] = 'sqlite:///quote.db'

# Database
db = SQLAlchemy(app)
migrate = Migrate(app, db)

# Flask Login
login_manager = LoginManager(app)

# Bcrypt
bcrypt = Bcrypt(app)

# Register Blueprints
from quoter.root.routes import root
app.register_blueprint(root)
from quoter.users.routes import users
app.register_blueprint(users)
from quoter.posts.routes import posts
app.register_blueprint(posts)

def create_app():
    return app

quoter/posts/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user

from quoter import db
from quoter.models.post import Post
from quoter.models.user import User

from .forms import CreateForm, LikeForm, UnlikeForm

posts = Blueprint('posts', __name__)


@login_required
@posts.route('/post', methods=["GET", "POST"])
def create():
    form = CreateForm()

    if form.validate_on_submit():
        content = form.content.data
        post = Post(content=content, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for("root.index"))

    return render_template("posts/create.html", form=form)

@posts.route("/post/<int:post_id>", methods=["GET", "POST"])
def post(post_id):
    post = Post.query.filter_by(id=post_id).first()

    form = None

    # Like/Unlike post
    if request.method == "POST":
        if current_user.is_authenticated:
            if current_user not in post.liked:
                current_user.likes.append(post)
            else:
                current_user.likes.remove(post)
            db.session.commit()
        else:
            # If no user is authenticated, redirect to register upon clicking Like button
            return redirect(url_for("users.register"))

    if post:
        user = User.query.filter_by(id=post.user_id).first()

        # Show Like/Unlike button depending on user's relationship with post
        if current_user.is_authenticated:
            if current_user in post.liked:
                form = UnlikeForm()
            else:
                form = LikeForm()

        return render_template("posts/post.html", post=post, user=user, post_id=post_id, form=form)

    return render_template("posts/post.html", post=post, post_id=post_id)

quoter/root/routes.py
from flask import Blueprint, render_template

from quoter.models.post import Post
from quoter.models.user import User

root = Blueprint("root", __name__)


@root.route("/")
def index():
    posts = Post.query.all()

    return render_template("root/index.html", posts=posts)

quoter/users/routes.py
from functools import wraps

from flask import Blueprint, redirect, url_for, render_template
from flask_login import current_user, login_user, login_required, logout_user

from quoter import login_manager, bcrypt, db
from quoter.models.user import User

from .forms import RegisterForm, LoginForm

users = Blueprint("users", __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).first()

def logout_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if current_user.is_authenticated:
            return redirect(url_for("root.index"))
        return f(*args, **kwargs)
    return decorated_function

@users.route("/register", methods=["GET", "POST"])
@logout_required
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        email = form.email.data
        username = form.username.data
        first_name = form.first_name.data
        last_name = form.last_name.data
        password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(email=email, username=username, first_name=first_name, last_name=last_name, password=password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("root.index"))
    return render_template("users/register.html", form=form)

@users.route("/login", methods=["GET", "POST"])
@logout_required
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user, form.remember.data)
                return redirect(url_for("root.index"))
            else:
                # TODO: Handle incorrect password
                pass
        else:
            # TODO: Handle incorrect username
            pass
    return render_template("users/login.html", form=form)

@users.route("/logout", methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    return render_template("users/logout.html")

@users.route("/profile/<username>")
def profile(username):
    user = User.query.filter_by(username=username).first()
    return render_template('users/profile.html', user=user, username=username)

quoter/templates/layouts/_formhelpers.html
{% macro render_field(field) %}
    {{ field.label }}
    {{ field }}
    {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    <br />
{% endmacro %}

quoter/templates/layouts/_navhelpers.html
{% macro render_link(href, label) %}
    <li>
        <a class="nav-link" href="{{ href }}">{{ label }}</a>
    </li>
{% endmacro %}

quoter/templates/layouts/base.html
<!doctype html>
<html>
    <head>
        <title>Quoter{% if self.title() %} | {% endif %}{% block title %}{% endblock %}</title>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- CDN Font -->
        <link href="https://fonts.cdnfonts.com/css/helvetica-neue-9" rel="stylesheet">
    </head>
    <body>
        {% include 'layouts/nav.html' %}
        {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
        {% endfor %}
        <section class="container">
            {% block content %}{% endblock %}
        </section>

        <!-- Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>

<style>
    @import url('https://fonts.cdnfonts.com/css/helvetica-neue-9');
</style>

quoter/templates/layouts/nav.html
{% from "layouts/_navhelpers.html" import render_link %}

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('root.index') }}">Quoter</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {{ render_link(url_for('root.index'), "Home") }}
                {% if current_user.is_authenticated %}
                    {{ render_link(url_for('users.profile', username=current_user.username), "Profile") }}
                    {{ render_link(url_for('posts.create'), "Post") }}
                    {{ render_link(url_for('users.logout'), "Logout") }}
                {% else %}
                    {{ render_link(url_for('users.register'), "Register") }}
                    {{ render_link(url_for('users.login'), "Login") }}
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

quoter/templates/posts/create.html
{% from "layouts/_formhelpers.html" import render_field %}

{% extends "layouts/base.html" %}

{% block content %}
    <form method="post">
        {{ form.csrf_token }}
        {{ render_field(form.content) }}
        {{ form.submit }}
    </form>
{% endblock %}

quoter/templates/posts/post.html
{% extends "layouts/base.html" %}

{% block content %}
    {% if post %}
        <h4>{{ post.user.username }}</h4>
        <p>{{ post.content }}</p>
        <p>Likes: {{ post.liked|length }}</p>
        <form method="post">
            {{ form.submit }}
        </form>
    {% else %}
        <h1>Post {{ post_id }} was not found.</h1>
    {% endif %}
{% endblock %}

quoter/templates/root/index.html
{% extends "layouts/base.html" %}

{% block content %}
    {% if posts %}
        <div class="border-top"></div>
        {% for post in posts %}
        <section class="container border-bottom mb-2">
            <div>
                <a href="{{ url_for('users.profile', username=post.user.username) }}" class="d-flex">
                    <img style="width: 7vh; height: 7vh;" class="rounded-circle border mt-2 mb-2 mr-2" src="{{ post.user.picture }}" />
                    <h4 class="align-self-center">@{{ post.user.username }}</h4>
                </a>
            </div>

            <div>
                <p>{{ post.content }}</p>
            </div>

            <h5>{{ post.date_posted }} UTC</h5>
        </section>
        {% endfor %}
    {% else %}
        <!-- TODO -->
    {% endif %}
{% endblock %}

quoter/templates/users/_profilehelpers.html
{% macro render_profile_main(user) %}
<section class="text-center border-bottom">
    <img style="width: 10vh; height: 10vh;" class="rounded-circle border mb-2" src="{{ user.picture }}" />
    <h3>@{{ user.username }}</h3>
    <h5>{{ user.first_name }} {{ user.last_name }}</h5>
</section>
<section class="border-bottom navbar-expand-lg">
    <ul class="navbar-nav mr-auto d-flex justify-content-around">
        <li class="nav-link">Activity</li>
        <li class="nav-link">Posts</li>
        <li class="nav-link">Liked</li>
    </ul>
</section>
{% endmacro %}

quoter/templates/users/login.html
{% from "layouts/_formhelpers.html" import render_field %}

{% extends "layouts/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <form method="post">
        {{ form.csrf_token }}
        {{ render_field(form.email) }}
        {{ render_field(form.password) }}
        {{ render_field(form.remember) }}
        {{ form.submit }}
    </form>
{% endblock %}

quoter/templates/users/logout.html
{% from "layouts/_formhelpers.html" import render_field %}

{% extends "layouts/base.html" %}

{% block title %}Logout{% endblock %}

{% block content %}
    <h1>Logged out</h1>
{% endblock %}

quoter/templates/users/profile.html
{% from "users/_profilehelpers.html" import render_profile_main %}

{% extends "layouts/base.html" %}

{% block content %}
    {% if user %}
        {{ render_profile_main(user) }}
    {% else %}
        <h1>User "{{ username }}" was not found.</h1>
    {% endif %}
{% endblock %}

quoter/templates/users/register.html
{% from "layouts/_formhelpers.html" import render_field %}

{% extends "layouts/base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
    <form method="post">
        {{ form.csrf_token }}
        {{ render_field(form.email) }}
        {{ render_field(form.username) }}
        {{ render_field(form.first_name) }}
        {{ render_field(form.last_name) }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit }}
    </form>
{% endblock %}